# Generated by Django 5.0.3 on 2024-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAFOND', '0002_news_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='coll_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='req_money',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=20),
            preserve_default=False,
        ),
    ]
