# Generated by Django 5.0.3 on 2024-05-08 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAFOND', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
